%dev.quarkus.http.port=8092

#quarkus.kafka.devservices.topic-partitions.execute-calculus=1

mp.messaging.incoming.flow-out-incoming.connector=smallrye-kafka
mp.messaging.incoming.flow-out-incoming.topic=flow-out
mp.messaging.incoming.flow-out-incoming.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
mp.messaging.incoming.flow-out-incoming.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.flow-out-incoming.auto.offset.reset=earliest

# ---- Quarkus Flow ----
# Optional, but nice to see logs when you hit workflows from Dev UI
quarkus.log.category."io.quarkiverse.flow".level=INFO